# Map Configurations
# Multiple maps with different paths and difficulty levels

maps:
  classic:
    name: "Classic Path"
    difficulty: "Easy"
    description: "Standard zigzag path - perfect for beginners"
    width: 800
    height: 500
    path:
      - { x: 0, y: 250 }
      - { x: 200, y: 250 }
      - { x: 200, y: 100 }
      - { x: 400, y: 100 }
      - { x: 400, y: 400 }
      - { x: 600, y: 400 }
      - { x: 600, y: 250 }
      - { x: 800, y: 250 }
    path_half_width: 20.0
    starting_gold: 100
    starting_lives: 20

  spiral:
    name: "Spiral Maze"
    difficulty: "Medium"
    description: "Spiral path from outside to center"
    width: 800
    height: 500
    path:
      - { x: 0, y: 50 }
      - { x: 700, y: 50 }
      - { x: 700, y: 450 }
      - { x: 100, y: 450 }
      - { x: 100, y: 150 }
      - { x: 600, y: 150 }
      - { x: 600, y: 350 }
      - { x: 200, y: 350 }
      - { x: 200, y: 250 }
      - { x: 400, y: 250 }
      - { x: 800, y: 250 }
    path_half_width: 20.0
    starting_gold: 120
    starting_lives: 18

  straight:
    name: "Highway Rush"
    difficulty: "Hard"
    description: "Short direct path - enemies move fast!"
    width: 800
    height: 500
    path:
      - { x: 0, y: 250 }
      - { x: 800, y: 250 }
    path_half_width: 25.0
    starting_gold: 150
    starting_lives: 15

  crossroads:
    name: "Crossroads"
    difficulty: "Medium"
    description: "Multiple turns and crossings"
    width: 800
    height: 500
    path:
      - { x: 0, y: 250 }
      - { x: 250, y: 250 }
      - { x: 250, y: 100 }
      - { x: 550, y: 100 }
      - { x: 550, y: 400 }
      - { x: 250, y: 400 }
      - { x: 250, y: 250 }
      - { x: 800, y: 250 }
    path_half_width: 20.0
    starting_gold: 110
    starting_lives: 18

  labyrinth:
    name: "Ancient Labyrinth"
    difficulty: "Hard"
    description: "Complex winding path through ancient ruins"
    width: 800
    height: 500
    path:
      - { x: 0, y: 450 }
      - { x: 150, y: 450 }
      - { x: 150, y: 350 }
      - { x: 300, y: 350 }
      - { x: 300, y: 150 }
      - { x: 150, y: 150 }
      - { x: 150, y: 50 }
      - { x: 450, y: 50 }
      - { x: 450, y: 250 }
      - { x: 600, y: 250 }
      - { x: 600, y: 450 }
      - { x: 800, y: 450 }
    path_half_width: 18.0
    starting_gold: 130
    starting_lives: 16

  islands:
    name: "Island Hopping"
    difficulty: "Expert"
    description: "Short segments between islands - strategic placement required"
    width: 800
    height: 500
    path:
      - { x: 0, y: 250 }
      - { x: 150, y: 250 }
      - { x: 150, y: 100 }
      - { x: 300, y: 100 }
      - { x: 300, y: 400 }
      - { x: 450, y: 400 }
      - { x: 450, y: 150 }
      - { x: 600, y: 150 }
      - { x: 600, y: 350 }
      - { x: 750, y: 350 }
      - { x: 750, y: 250 }
      - { x: 800, y: 250 }
    path_half_width: 20.0
    starting_gold: 140
    starting_lives: 12
